### ISSUE TITLE
[feat] pseudo-array

### ISSUE THREAD

**Issue by CoffeeChaton** [CoffeeChaton/vscode-autohotkey-NekoHelp#11]
# pseudo-array

from [#8-3](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/issues/8)

> And I think this will be a tricky one, given that is an AHK-ism. `last` is marked as unused, while it is unused there is no value assigned to the variable, it just creates a pseudo-array (`lastX`, `lastY`, `lastW`, `lastH`).
>
> ```ahk
> GuiControlGet last, Pos, ComboBox1
> Gui Add, Edit, % "x" lastX " y" lastY
> ```
>
> From the top of my head, I can think of two other commands.
>
> `SysGet` is the same (`mon` doesn't get a value):
>
> ```ahk
> SysGet mon, Monitor
> OutputDebug % monRight "x" monBottom
> ```
>
> ↓↓↓ _stuff below are for context_ ↓↓↓
>
> `WinGet` while retrieving a list of windows does get a value:
>
> ```ahk
> WinGet wList, List, A
> OutputDebug % wList1
> ```
>
> To be fair, that one can be scrapped as I never seen it used in other form than this one:
>
> ```ahk
> WinGet wList, List, A
> loop % wList {
>     hWnd := "ahk_id" wList%A_Index%
>     OutputDebug % hWnd
> }
> ```

ahk-v1.1 documentation, with _OutputVar_'s own name (to form a [pseudo-array](https://www.autohotkey.com/docs/v1/misc/Arrays.htm#pseudo)), It seems that there is no unified signature like `Out` or `Output`, which is convenient for me to search from the original html code, i am try to use it c++ code to search `pseudo-array`, but before that, if you can help me view the v1.1 document, maybe it will be a better way! Thanks!❤

I plan to manually add the above 3 rules to the parser, but I didn’t think of the built-in cmd also use a pseudo-array.

```c++
#define OUTPUT_VAR (*sArgVar) // ExpandArgs() has ensured this first ArgVar is always initialized, so there's never any need to check mArgc > 0.
```

**Comment by CoffeeChaton** [comment]
# pseudo-array

minimal repeat

## `GuiControlGet` and sub-cmd is `Pos`

```ahk
#Requires AutoHotkey v1.1.33+
; https://www.autohotkey.com/docs/v1/lib/GuiControlGet.htm#Pos
; https://www.autohotkey.com/board/topic/72665-ahk-l-1151-problem-with-guicontrolget-outputvar-pos/

Gui Add, Tab, hwndhwTabCtrl
GuiControlGet last, Pos , %hwTabCtrl%

; last[0 of 0]:
; lastH[3 of 3]: number
; lastW[3 of 3]: number
; lastX[2 of 3]: number
; lastY[1 of 3]: number

ListVars
MsgBox % "observe ListVars"
```

## `SysGet` and sub-cmd is `Monitor` or `MonitorWorkArea`

```ahk
#Requires AutoHotkey v1.1.33+

; https://www.autohotkey.com/docs/v1/lib/SysGet.htm#Monitor
SysGet OutputVar, Monitor
; SysGet OutputVar, MonitorWorkArea


ListVars

; OutputVar[0 of 0]:
; OutputVarBottom[4 of 7]:
; OutputVarLeft[1 of 3]:
; OutputVarRight[4 of 7]:
; OutputVarTop[1 of 3]:

MsgBox % "observe ListVars"
```

## `WinGet` and sub-cmd is `List`

```ahk
#Requires AutoHotkey v1.1.33+

; https://www.autohotkey.com/docs/v1/lib/WinGet.htm#List
WinGet OutputVar, List ; To retrieve all windows on the entire system, omit all four title/text parameters.

ListVars

; OutputVar[0 of 0]:
; OutputVar1[0 of 0]:
; OutputVar2[0 of 0]:
; OutputVar3[0 of 0]:
; ....

MsgBox % "observe ListVars"
```

## TODO list

- [x] Disable diagnosis
- [x] hover at it
- [x] goto-def
- [ ] find-all-ref
- [x] Completion of it.
- [x] semantic-highlight of it
- [ ] global-var vs local-var
- [x] handle references

**Comment by CoffeeChaton** [comment]
[StringSplit](https://www.autohotkey.com/docs/v1/lib/StringSplit.htm)

```ahk

#Requires AutoHotkey v1.1.33+
#Warn All, MsgBox

Colors := "red,green,blue"
StringSplit, ColorArray, Colors, `,

ListVars
; Global Variables (alphabetical)
; --------------------------------------------------
; 0[1 of 3]: 0
; A_Args: Object object
; ColorArray0[1 of 3]: 3
; ColorArray1[3 of 3]: red
; ColorArray2[5 of 7]: green
; ColorArray3[4 of 7]: blue
; Colors[14 of 63]: red, green, blue
; ErrorLevel[1 of 3]: 0

MsgBox, % "text"
```

**Comment by CoffeeChaton** [comment]
- find-all-ref
- global-var vs local-var

I don’t know how to implement it better
