### ISSUE TITLE
[feat] 中文文档 /nls Built-in doc Multilingual Program

### ISSUE THREAD

**Issue by CoffeeChaton** [CoffeeChaton/vscode-autohotkey-NekoHelp#45]
# Feat Provide

## 🔎 Search keywords

nls / 中文文档 / Multilingual 

## Additional context

1. sort out the framework.
2. Translate documents.
3. Translation progress and content of each dictionary, detailed.json.

## milestone(framework)
 - [x]  A_Variables.data.ts
 - [x]  Ahk2exe.data.ts
 - ~[ ]  ahkSnippets.data.ts~ // not need
 - [x]  BiVariables.data.ts
 - ~[ ]  color.data.ts~ // not need
 - [x]  Command.data.ts
 - [x]  configUI.data.ts
 - [ ]  Control.data.ts
 - [ ]  ControlGet.data.ts
 - ~[ ]  data_index.data.ts~ // not need
 - [ ]  declaration.data.ts
 - [x]  Directives.data.ts
 - [x]  foc.data.ts
 - [x]  focEx.data.ts
 - [x]  function.data.ts
 - [ ]  Gui.data.ts
 - [ ]  GuiControl.data.ts
 - [ ]  HotStringsOptions.data.ts
 - ~[ ]  keyList.data.ts~ // not need
 - [ ]  Menu.data.ts
 - [ ]  nekoExComment.data.ts
 - [ ]  operator.data.ts
 - [ ]  ~~RegRootKey.data.ts~~
 - ~[ ]  semanticFoc.data.ts~ // not need
 - [ ]  SysGet.data.ts
 - ~[ ]  Windows_Messages.data.ts~ // not need
 - [ ]  WindowsClassIdentifiers.data.ts
 - [ ]  WinGet.data.ts
 - [ ]  WinSet.data.ts
 - [ ]  WinTitleParameter.data.ts

## provide

- gotoDef
- hover
- etc

**Comment by CoffeeChaton** [comment]
https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/assets/63182963/9e593b38-2126-4738-9b3d-698e34ca3f07

built-in function gotoDef
