### ISSUE TITLE
[TODO] event.FileRenameEvent

### ISSUE THREAD

**Issue by CoffeeChaton** [CoffeeChaton/vscode-autohotkey-NekoHelp#5]
# event.FileRenameEvent
```jsonc
// settings.json
{
    "AhkNekoHelp.event.FileRenameEvent":0
}
```

| option                  | describe                         |
| ----------------------- | :------------------------------- |
| 0(default)              | log at background                |
| 1                       | log and show                     |
| 2(`Alpha test options`) | log and try to Rename `#Include` |

## option 0

just log at background, if you want to undo, you can try to open _OUTPUT BOX_ (default via `ctrl shift u`) to see log.

## option 1

log and show, if you often renamed/move files, but forgot to fix `#Include`, I recommend this.

## option 2

1. **warn** this option is `Alpha test`, and not support at _file-path_ or `#Include` has any `special char` (like `;` or `,`).
2. In any case, please manually confirm whether there is a wrong way to change, or should be changed but no.

- [ ] support move fold
- [x] support move file
- [ ] support rename fold
- [x] try to auto-edit rename file

exp : [mp4 18sec 190KB]

[mp4 18sec 190KB](https://user-images.githubusercontent.com/63182963/224714594-6628dc06-f585-44d4-816e-ef1692a03bcf.mp4)

**Comment by CoffeeChaton** [comment]
Temporarily closed

**Comment by CoffeeChaton** [comment]
<https://youtu.be/mV6ziP7Vt_M>

```jsonc
// settings.json
{
    "AhkNekoHelp.event.FileRenameEvent":2
}
```

support one file move event, and auto fix `#Include`

**Comment by CoffeeChaton** [comment]
try support multiple files move event, and auto fix `#Include`
at `v0.0.62`(2024-06-XX)

**Comment by CoffeeChaton** [comment]
vscode not probvide a event like `vscode.workspace.onDidRenameFiles` for `move fold` / `rename fold`.
I also don't want to implement it with SetTimer,
May only provide manual commands.
