### ISSUE TITLE
Some comments...

### ISSUE THREAD

**Issue by anonymous1184** [CoffeeChaton/vscode-autohotkey-NekoHelp#7]
Since you actually care about the extension, here is a small list of things I've discovered over the short time I've used it. Feel free to ignore any (all?) of them, as they might not align with your vision for the project.

Thank you for your time!

---

Getting the `seed` argument for the `Random` command out of a function, warns a \#500:
```ahk
Random ,, % Epoch()
```

Using an unquoted string (forced expression is OK) previously used as variable, show info \#502.
```ahk
GuiControlGet secret,, Edit1
; ...
Gui Show,, Secret (Click to copy)
```

For both, an ignore comment works just fine as the edge cases they are.

---

Something to think about is that in v1.1 the initial comma after a command is optional, while in v2 is not allowed. Removing the comma from autocompletion would make transition easier, not to mention add cohesion.

At nice compromise will be to set the final tab-stop of autocompletion, like the `#Warn` directive currently has it:
```ahk
#Warn,$0 ${1|All,Unreachable,ClassOverwrite,LocalSameAsGlobal,UseEnv,UseUnsetLocal,UseUnsetGlobal|}, ${2|MsgBox,StdOut,OutputDebug,Off|}
```
The cursor is set at the comma, allowing the user to either keep it or remove it.

---

The snippets show perfectly the help, using the brackets exactly like in the documentation (and as per spec), marking what is optional and what not. But at the moment of adding the text from the autocomplete, the brackets are also pasted.

Some, as a stand-alone command, need the removal of everything: space, comma, bracket, value and closing bracket
```ahk
ListLines [, On] ; From
ListLines        ; To
```

And with an argument: bracket, comma, space and final bracket
```ahk
ListLines [, On] ; From
ListLines On     ; To
```

In some occasions, one ends up wasting more time adjusting than typing it in the first place.

A more complex example is `WinGetTile`, that has 1 required parameter and 4 optional:
```ahk
WinGetTitle, OutputVar [, WinTitle, WinText, ExcludeTitle, ExcludeText] ; As it is
WinGetTitle OutputVar                                                   ; No optional
```

That I don't know how to explain, but with code:
```json
"WinGetTitle": {
    "body": "WinGetTitle ${1:OutputVar}${2:, ${3:WinTitle}, ${4:WinText}, ${5:ExcludeTitle}, ${6:ExcludeText}}",
    "prefix": "wgt"
}
```
The first <kbd>Tab</kbd> moves the cursor to the `OutputVariable`, the next one to the very end where you can delete all the optional parameters, or <kbd>Tab</kbd> again to navigate between each parameter and set the appropriate argument.

That way is easier than navigate with the keyboard to remove what's not needed.

And this one can also be a compromise by setting the last tab-stop right before the bracket to manually delete.

---

There are a couple of commands that have a space after the comma (`ControlFocus` for example). And some that have all the parameters marked as optional (`SetTimer`, `FileAppend`, `SetKeyDelay`), I guess for the super rare occasions where they are not needed, but most of the time one adds them anyway.

`OutputDebug` lacks the last quote, and `#Requires` adds 2 times the directive.

---

By no means are complaints, just little things I've noticed, and of course some food for thought regarding the removal of the optional comma.

Again, thanks for your time and feel free to disregard what's not within scope.

**Comment by CoffeeChaton** [comment]
# reply

## part 1

```ahk
Random,, % Epoch()
```

this is my parsing error of [Command OutputVar](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/main/src/tools/Built-in/CommandOutPut.global.test.ts#L5), i will fix it at next version.

## part 2

```ahk
GuiControlGet secret,, Edit1

Gui Show,, Secret (Click to copy)
;          ^^^^^^^^^^^^^^^^^^^^^^
MsgBox Secret foo() 1 + 2 if (a > 0) then new class()
;      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

1. the `^` is string, but regex-highlight and my semantic-parser is not...
2. This is one of my ultimate goals. In the editor, let ahk-v1.1 users don't need to think about whether this is an expression or a legacy string.
3. But now, I only achieve the correct highlighting of the legacy, even when vscode does not call my extension to run [semantic-highlight](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) (EXP: like markdown-code-block, or hover), these are only hosted by [syntax-highlight](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#semantic-theming) which relies on regex which is difficult to maintain.
4. Until I get to `0.1.0`, I can only advise users to use [forced expression](https://www.autohotkey.com/docs/v1/Language.htm#-expression) `% Expression` to avoid weird highlighting/parsing exceptions.

## part 3

> At nice compromise will be to set the final tab-stop of autocompletion, like the `#Warn` directive currently has it:

Great idea to let the user choose, but I need some time to work.

## part 4

> Some, as a stand-alone command, need the removal of everything: space, comma, bracket, value and closing bracket

```ahk
ListLines ; not any Arg
ListLines On ; Arg1 is On
ListLines Off ; Arg1 is Off
```

Some commands, when I write rules, I without thinking to use doc to write, but it is inconvenient when editing vscode. If there is a better way, I will manually correct it, just like `MsgBox` and `#warn`, If you have a better idea please let me know.

![q](https://user-images.githubusercontent.com/63182963/225655209-90299388-9491-4f47-b806-e9db3aaf31e1.png)

## part 5

> A more complex example is WinGetTile, that has 1 required parameter and 4 optional:
>
> ```ahk
> "WinGetTitle": {
>    "body": "WinGetTitle ${1:OutputVar}${2:, ${3:WinTitle}, ${4:WinText}, ${5:ExcludeTitle}, ${6:ExcludeText}}",
>    "prefix": "wgt"
> }
> ```

This edit is awesome! I will change my snippet, any good idea of other commands? But i need some time to fix my unit-test.

## part 6

### part 6-1

> There are a couple of commands that have a space after the comma (ControlFocus for example).

i will fix `ControlFocus`, if you find a similar problem, please let me know and I will fix it.

### part 6-2

> `SetTimer`, `FileAppend`, `SetKeyDelay`

I think your suggestion is right, I can hardly think of these 3 commands without parameters, and intend to add exception conditions to unit tests.

### part 6-3

> `OutputDebug` lacks the last quote, and `#Requires` adds 2 times the directive.

i will fix it, because I manually enter the rules, sometimes there are mistakes.

## plan

- [x] part 1, parsing error of [Command OutputVar](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/main/src/tools/Built-in/CommandOutPut.global.test.ts#L5)
- [x] ~~part 2~~, my ultimate goals, not plan to list here.
- [x] part 3, need some time to fix unit-test.
- [x] part 4, fix `ListLines` now.
- [x] part 5, plan to change `WinGetTitle`
- [x] part 6-1, will fix `ControlFocus`
- [x] part 6-2, will fix `SetTimer`, `FileAppend`, `SetKeyDelay`
- [x] part 6-3, fix `OutputDebug` and `#Requires` now.


Thank you very much for your report, if you have any good ideas, or if you find that my parsing is wrong, please let me know Thanks!

**Comment by anonymous1184** [comment]
Thanks a lot for the detailed reply, and I'll gladly help you with anything I can. I tried to do the same with another extension, but the owner liked more create hundreds of tickets rather than fix the thing.

If you want, I can go through each of the commands and check for problems. Also, I can suggest a fix according to the docs. That I can pass to you, and so you can do your own process of vetting and update anything that needs it.

**Comment by CoffeeChaton** [comment]
part 3-2
  > in v1.1 the initial comma after a command is optional

  add select CodeAction(_yellow light bulb_) to format like it.

  1. for default-format, users generally do not check whether the results of formatting changes are normal, so for the sake of conservatism , my default configuration is to adjust only the indent (the blank symbol in front)
  2. for `Alpha test options` format, I want to think about how to stitch this command to the format function ().
  3. Now only provide a small light bulb for formatting, and output some logs.


[mp4 1.18MB 31sec](https://user-images.githubusercontent.com/63182963/226155927-ded20845-1e4c-474f-8993-d49c02598913.mp4)

**Comment by CoffeeChaton** [comment]
- [x] part 1, parsing error of Command OutputVar
  - [x] ~~part 3-1, need some time to fix unit-test, Help users tab to `$0`~~, `$0` is need to use at part 4-2
  - [x] part 3-2, add select CodeAction(_yellow light bulb_) to format it
  - [x] part 4-1, fix `ListLines` now
  - [x] part 4-2, let `[` -> `,[$0` , this helps users to tab to delete this, and using unit-test.
  - [x] part 5, fix `WinGetTitle`
  - [x] part 6-1, fix `ControlFocus` , and add unit_test
  - [x] part 6-2, fix `SetTimer`, `FileAppend`, `SetKeyDelay`
  - [x] part 6-3, fix `OutputDebug` and `#Requires` now.
 
part 4-2
  > But at the moment of adding the text from the autocomplete, the brackets are also pasted.

  1. This is by design, because I found that when I edited the parameters, I forgot that those parameters were optional, so I changed to manually delete `[]` after the [2022-11-10](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp-Old/commit/ba17b8eb9c146a09a941bf3214522706f4e00891).
  2. I plan to let `[` -> `,[$0` , this helps users to tab to delete this, and using unit-test
  3. `]` it can use `end` key to del, so no need for $0

let `Click [, ${1:Options}]` -> `Click,[$0 ${1:Options}]` or any good idea?

**Comment by CoffeeChaton** [comment]
## about Part 3 - `#Directive`

I noticed that the online documentation for ahk-v1.1 does not include a first optional comma after the `#Directive`, unlike `Command`. Since the way `#Directive` is recognized is relatively straightforward, I am confident in integrating it directly into the format and modifying the fill fragment at `v0.0.31`.

  - [x] part 3-3, add format opt, format the signature format for the ahk-v1.1 online documentation, by remove [#Directive](https://www.autohotkey.com/docs/v1/lib/#hash) first optional comma, read doc [removeFirstCommaDirective](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/main/note/config/format.removeFirstCommaDirective.md)
  - [x] part 3-4, fix: Adjusted completion - the part about `#Directive`, conforming to the signature of the document (meaning there is no first optional comma).
 
 
## to do list
 - [x] part 3-5, add format switch of `Command` first optional comma, exp : `MsgBox, % "text"` <--> `MsgBox % "text"`
 - [x] part 4-2, let `Click [, ${1:Options}]` -> `Click,[$0 ${1:Options}]`

**Comment by anonymous1184** [comment]
Awesome! Is incredible how quick you have tackled this, wish I had reach sooner.

---

**EDIT:** Removed because it was out of context.

**Comment by CoffeeChaton** [comment]
> Awesome! Is incredible how quick you have tackled this, wish I had reach sooner. Also, find a couple others 😳

Thank you for your praise, I want to make people who are left in ahk-v1.1 feel happy to edit/maintain ahkv1.1, but the current #7 has too many extended issues, for follow-up management tracking , will cause disturbance, if possible, please help me open a new topic

**Comment by anonymous1184** [comment]
@CoffeeChaton will do.

**Comment by CoffeeChaton** [comment]
> - part 3-5, add format switch of Command first optional comma, exp : `MsgBox, % "text"` <--> `MsgBox % "text"`

Now you can use vscode `editor.formatOnType` and my `AhkNekoHelp.format.removeFirstCommaCommand` to auto remove first Command after enter.

> - part 4-2, let `Click [, ${1:Options}]` -> `Click,[$0 ${1:Options}]`

I plan to completely remove all square bracket prompts after extending [signature](https://www.youtube.com/watch?v=WcMzNcVWcYA) prompts to traditional commands, but before that, if you have other good ideas, please let me know, thanks!

**Comment by anonymous1184** [comment]
Looking awesome, I just wish I had this years ago. Your extension made me step down my dislike of v1.1 syntax and start fixing pending issues with v1.1 projects.

Thanks a lot for all your efforts.

**Comment by CoffeeChaton** [comment]
<https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/66e6eec4f6ec31447ddd0ec7842fad81815646db/TODO/diagCase.ahk#L11-L17>

If you want to review your 1.1 code, I suggest you check `if ()` is executed after the same line, this is a common pitfall, but I don't know how to write diagnostics, instructions, documentation.

and

<https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp/blob/main/note/code507.md>

```ahk
if 0 < 3  ; The left side of a non-expression if-statement is always the name of a variable.
{
   MsgBox This script requires at least 3 incoming parameters but it only received %0%.
   ExitApp
}
```

**Comment by anonymous1184** [comment]
With fixing, I mean pending updates and flow improvements.

Fortunately for me, I have a somewhat strict style that helps me avoid issues without even realizing it. In fact, over time I've been relaxing from Linux Kernel standard to less strict (indentation levels and line length).

That helps a lot when migrating from v1.1 to v2; the job is basically just a few edits, for example:

<https://gist.github.com/58d2b141be2608a2f7d03a982e552a71>

I'm currently giving final touches and doing intensive testing on something, gonna let you know when it's done. And that will be thanks to you.
